name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install
        run: yarn --pure-lockfile

      - name: Lint - Prettier
        run: yarn lint:prettier

      - name: Lint - ESLint
        continue-on-error: true
        run: yarn lint:eslint

      - name: Build
        run: yarn build
